name: memory_companion
description: "The app that remembers for you what your brain can no longer remember"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  riverpod: ^3.4.2
  flutter_riverpod: ^3.0.2
  flutter_localization: ^0.4.1
  intl: ^0.20.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo_mascota.png
  #   - images/a_dot_ham.jpeg
